package com.google.android.gms.internal.mlkit_vision_common;

import androidx.customview.widget.FocusStrategy;
import androidx.customview.widget.ViewDragHelper;
import androidx.dynamicanimation.animation.FloatPropertyCompat;
import androidx.emoji2.text.DefaultEmojiCompatConfig;
import androidx.emoji2.text.MetadataListReader;
import androidx.exifinterface.media.ExifInterfaceUtils;
import androidx.fragment.app.FragmentAnim;
import androidx.lifecycle.compose.FlowExtKt;
import androidx.lifecycle.compose.LifecycleEffectKt;
import androidx.lifecycle.viewmodel.compose.ViewModelKt;
import androidx.navigation.NavArgumentKt;
import androidx.navigation.NavControllerViewModel;
import androidx.navigation.NavDestination;
import androidx.navigation.NavGraph;
import androidx.navigation.NavOptionsBuilderKt;
import androidx.navigation.NavigatorProvider;
import androidx.navigation.compose.DialogHostKt;
import androidx.navigation.compose.NavBackStackEntryProviderKt;
import androidx.navigation.compose.NavGraphBuilderKt;
import androidx.navigation.compose.NavHostControllerKt;
import androidx.navigation.compose.NavHostKt;
import androidx.navigationevent.NavigationEventInfo;
import androidx.navigationevent.NavigationEventTransitionState;
import androidx.navigationevent.NavigationEvent_androidKt;
import androidx.recyclerview.widget.ScrollbarHelper;
import androidx.room.util.CursorUtil;
import androidx.room.util.DBUtil;
import androidx.room.util.TableInfo;
import androidx.room.util.TableInfoKt;
import androidx.savedstate.SavedStateReader;
import androidx.savedstate.ViewTreeSavedStateRegistryOwner;
import androidx.sqlite.db.SimpleSQLiteQuery$Companion;
import androidx.tracing.Trace;
import androidx.transition.Transition;
import androidx.transition.ViewGroupUtils;
import androidx.transition.ViewUtilsApi19;
import androidx.viewbinding.ViewBindings;
import androidx.work.Operation;
import androidx.work.WorkContinuation;
import androidx.work.impl.WorkDatabasePathHelper;
import androidx.work.impl.WorkerUpdater;
import androidx.work.impl.model.WorkSpecKt;
import androidx.work.impl.model.WorkTypeConverters;
import androidx.work.impl.utils.EnqueueUtilsKt;
import coil.ImageLoaders;
import coil.decode.DecodeUtils;
import coil.decode.ImageSource$Metadata;
import coil.network.CacheStrategy;
import coil.size.Dimension;
import coil.util.Bitmaps;
import coil.util.Collections;
import coil.util.DrawableUtils;
import coil.util.FileSystems;
import coil.util.Lifecycles;
import coil.util.SvgUtils;
import com.github.kr328.clash.ApkDownloader;
import com.github.kr328.clash.MainApplication;
import com.github.kr328.clash.common.compat.ContextKt;
import com.github.kr328.clash.common.compat.IntentsKt;
import com.github.kr328.clash.common.compat.TvKt;
import com.github.kr328.clash.common.util.ComponentsKt;
import com.github.kr328.clash.common.util.IntentKt;
import com.github.kr328.clash.common.util.ParcelableKt;
import com.github.kr328.clash.compose.ApkBrokenScreenKt;
import com.github.kr328.clash.compose.AppCrashedScreenKt;
import com.github.kr328.clash.compose.FilesScreenKt;
import com.github.kr328.clash.compose.HwidLimitDialogKt;
import com.github.kr328.clash.compose.LogcatScreenKt;
import com.github.kr328.clash.compose.LogsScreenKt;
import com.github.kr328.clash.compose.MainAppKt;
import com.github.kr328.clash.compose.PropertiesScreenKt;
import com.github.kr328.clash.compose.ProvidersScreenKt;
import com.github.kr328.clash.compose.UpdateDialogKt;
import com.github.kr328.clash.compose.home.HomeScreenKt;
import com.github.kr328.clash.compose.profiles.ProfileCardKt;
import com.github.kr328.clash.compose.proxy.ProxyScreenKt;
import com.github.kr328.clash.compose.qrcode.TvQrCodeSheetKt;
import com.github.kr328.clash.compose.util.FormatKt;
import com.github.kr328.clash.compose.util.TvGlassTabRowKt;
import com.github.kr328.clash.core.util.TrafficKt;
import com.github.kr328.clash.design.model.LogFile;
import com.github.kr328.clash.design.util.I18nKt;
import com.github.kr328.clash.service.ProfileProcessorKt;
import com.github.kr328.clash.service.StatusProvider;
import com.github.kr328.clash.service.data.DaosKt;
import com.github.kr328.clash.service.document.Paths;
import com.github.kr328.clash.service.util.BroadcastKt;
import com.github.kr328.clash.service.util.CoroutineKt;
import com.github.kr328.clash.service.util.DatabaseKt;
import com.github.kr328.clash.service.util.DeviceInfoKt;
import com.github.kr328.clash.service.util.NetKt;
import com.github.kr328.clash.util.ClashKt;
import com.github.kr328.clash.util.ContentKt;
import com.github.kr328.clash.util.LocalNetworkKt;
import com.github.kr328.clash.util.QrCodeGeneratorKt;
import com.github.kr328.clash.util.RemoteKt;
import com.github.kr328.kaidl.SuspendTransactionKt;
import com.google.android.datatransport.Transformer;
import com.google.android.datatransport.cct.StringMerger;
import com.google.android.gms.common.api.internal.TaskUtil;
import com.google.android.gms.common.util.DeviceProperties;
import com.google.android.gms.internal.mlkit_common.zzt;
import com.google.android.gms.signin.zaa;
import com.google.firebase.encoders.config.EncoderConfig;

/* JADX INFO: compiled from: r8-map-id-642a9409e8c86705d83235ec931e7b4e3b870bec9858ab19ec33568b7f2d7797 */
/* JADX INFO: loaded from: classes.dex */
public final class zzmw implements Transformer {
    public static zzmw zza;
    public static final zzmw zza$1 = new zzmw(1);
    public static final /* synthetic */ zzmw zza$2 = new zzmw(2);
    public static final /* synthetic */ zzmw zza$3 = new zzmw(3);
    public final /* synthetic */ int $r8$classId;

    public /* synthetic */ zzmw(int i) {
        this.$r8$classId = i;
    }

    public static synchronized void zza() {
        if (zza == null) {
            zza = new zzmw(0);
        }
    }

    @Override // com.google.android.datatransport.Transformer
    public Object apply(Object obj) {
        switch (this.$r8$classId) {
            case 2:
                break;
        }
        return (byte[]) obj;
    }

    public void configure(EncoderConfig encoderConfig) {
        encoderConfig.registerEncoder(zziy.class, zzeo.zza);
        encoderConfig.registerEncoder(zzla.class, zzgu.zza);
        encoderConfig.registerEncoder(IntentKt.class, zzep.zza);
        encoderConfig.registerEncoder(AppCrashedScreenKt.class, zzer.zza);
        encoderConfig.registerEncoder(ParcelableKt.class, zzeq.zza);
        encoderConfig.registerEncoder(ApkBrokenScreenKt.class, zzes.zza);
        encoderConfig.registerEncoder(ImageLoaders.class, zzdr.zza);
        encoderConfig.registerEncoder(zzhx.class, zzdq.zza);
        encoderConfig.registerEncoder(MainApplication.Companion.class, zzeh.zza);
        encoderConfig.registerEncoder(ClashKt.class, zzgm.zza);
        encoderConfig.registerEncoder(EnqueueUtilsKt.class, zzdp.zza);
        encoderConfig.registerEncoder(WorkTypeConverters.class, zzdo.zza);
        encoderConfig.registerEncoder(HomeScreenKt.class, zzfd.zza);
        encoderConfig.registerEncoder(zzlu.class, zzeb.zza);
        encoderConfig.registerEncoder(DrawableUtils.class, zzee.zza);
        encoderConfig.registerEncoder(Lifecycles.class, zzea.zza);
        encoderConfig.registerEncoder(zzjm.class, zzfe.zza);
        encoderConfig.registerEncoder(DatabaseKt.class, zzgj.zza);
        encoderConfig.registerEncoder(DeviceInfoKt.class, zzgk.zza);
        encoderConfig.registerEncoder(CoroutineKt.class, zzgi.zza);
        encoderConfig.registerEncoder(LogsScreenKt.class, zzey.zza);
        encoderConfig.registerEncoder(zzlt.class, zzcy.zza);
        encoderConfig.registerEncoder(MainAppKt.class, zzez.zza);
        encoderConfig.registerEncoder(zzju.class, zzfm.zza);
        encoderConfig.registerEncoder(FormatKt.class, zzfp.zza);
        encoderConfig.registerEncoder(zzjw.class, zzfo.zza);
        encoderConfig.registerEncoder(zzjv.class, zzfn.zza);
        encoderConfig.registerEncoder(zzkg.class, zzfy.zza);
        encoderConfig.registerEncoder(zzkh.class, zzfz.zza);
        encoderConfig.registerEncoder(I18nKt.class, zzgb.zza);
        encoderConfig.registerEncoder(LogFile.Companion.class, zzga.zza);
        encoderConfig.registerEncoder(LogcatScreenKt.class, zzex.zza);
        encoderConfig.registerEncoder(ProfileProcessorKt.class, zzgc.zza);
        encoderConfig.registerEncoder(StatusProvider.Companion.class, zzgd.zza);
        encoderConfig.registerEncoder(zzkm.class, zzge.zza);
        encoderConfig.registerEncoder(DaosKt.class, zzgf.zza);
        encoderConfig.registerEncoder(BroadcastKt.class, zzgg.zza);
        encoderConfig.registerEncoder(Paths.class, zzgh.zza);
        encoderConfig.registerEncoder(zzkf.class, zzfu.zza);
        encoderConfig.registerEncoder(TvKt.class, zzem.zza);
        encoderConfig.registerEncoder(zzkd.class, zzfw.zza);
        encoderConfig.registerEncoder(zzkc.class, zzfv.zza);
        encoderConfig.registerEncoder(zzke.class, zzfx.zza);
        encoderConfig.registerEncoder(NetKt.class, zzgl.zza);
        encoderConfig.registerEncoder(TaskUtil.class, zzha.zza);
        encoderConfig.registerEncoder(SimpleSQLiteQuery$Companion.class, zzdd.zza);
        encoderConfig.registerEncoder(SavedStateReader.class, zzdb.zza);
        encoderConfig.registerEncoder(TableInfoKt.class, zzda.zza);
        encoderConfig.registerEncoder(ViewTreeSavedStateRegistryOwner.class, zzdc.zza);
        encoderConfig.registerEncoder(Transition.EpicenterCallback.class, zzdf.zza);
        encoderConfig.registerEncoder(Trace.class, zzde.zza);
        encoderConfig.registerEncoder(ViewGroupUtils.class, zzdg.zza);
        encoderConfig.registerEncoder(ViewUtilsApi19.class, zzdh.zza);
        encoderConfig.registerEncoder(ViewBindings.class, zzdi.zza);
        encoderConfig.registerEncoder(Operation.State.class, zzdj.zza);
        encoderConfig.registerEncoder(WorkContinuation.class, zzdk.zza);
        encoderConfig.registerEncoder(NavigationEvent_androidKt.class, zzcu.zza);
        encoderConfig.registerEncoder(CursorUtil.class, zzcw.zza);
        encoderConfig.registerEncoder(ScrollbarHelper.class, zzcv.zza);
        encoderConfig.registerEncoder(ContextKt.class, zzek.zza);
        encoderConfig.registerEncoder(DecodeUtils.class, zzds.zza);
        encoderConfig.registerEncoder(FloatPropertyCompat.class, zzbu.zza);
        encoderConfig.registerEncoder(ViewDragHelper.Callback.class, zzbv.zza);
        encoderConfig.registerEncoder(Collections.class, zzdy.zza);
        encoderConfig.registerEncoder(zzat.class, zzbw.zza);
        encoderConfig.registerEncoder(DefaultEmojiCompatConfig.class, zzbx.zza);
        encoderConfig.registerEncoder(FlowExtKt.class, zzcc.zza);
        encoderConfig.registerEncoder(FragmentAnim.class, zzcd.zza);
        encoderConfig.registerEncoder(MetadataListReader.class, zzby.zza);
        encoderConfig.registerEncoder(zzau.class, zzbz.zza);
        encoderConfig.registerEncoder(NavDestination.Companion.class, zzci.zza);
        encoderConfig.registerEncoder(NavControllerViewModel.Companion.class, zzcj.zza);
        encoderConfig.registerEncoder(DialogHostKt.class, zzcm.zza);
        encoderConfig.registerEncoder(NavigatorProvider.Companion.class, zzcn.zza);
        encoderConfig.registerEncoder(NavigationEventTransitionState.class, zzcs.zza);
        encoderConfig.registerEncoder(NavigationEventInfo.class, zzct.zza);
        encoderConfig.registerEncoder(NavGraphBuilderKt.class, zzco.zza);
        encoderConfig.registerEncoder(NavBackStackEntryProviderKt.class, zzcp.zza);
        encoderConfig.registerEncoder(NavHostKt.class, zzcq.zza);
        encoderConfig.registerEncoder(NavHostControllerKt.class, zzcr.zza);
        encoderConfig.registerEncoder(zzlo.class, zzgp.zza);
        encoderConfig.registerEncoder(zzlh.class, zzdt.zza);
        encoderConfig.registerEncoder(zzt.class, zzew.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzak.class, zzev.zza);
        encoderConfig.registerEncoder(zzli.class, zzec.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzy.class, zzgo.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzu.class, zzgn.zza);
        encoderConfig.registerEncoder(zzlp.class, zzgq.zza);
        encoderConfig.registerEncoder(DeviceProperties.class, zzei.zza);
        encoderConfig.registerEncoder(zzls.class, zzhc.zza);
        encoderConfig.registerEncoder(zzlr.class, zzhd.zza);
        encoderConfig.registerEncoder(zzlq.class, zzhb.zza);
        encoderConfig.registerEncoder(ContentKt.class, zzgr.zza);
        encoderConfig.registerEncoder(zziq.class, zzej.zza);
        encoderConfig.registerEncoder(ComponentsKt.class, zzen.zza);
        encoderConfig.registerEncoder(TableInfo.Column.Companion.class, zzcz.zza);
        encoderConfig.registerEncoder(zzik.class, zzef.zza);
        encoderConfig.registerEncoder(IntentsKt.class, zzel.zza);
        encoderConfig.registerEncoder(FileSystems.class, zzdz.zza);
        encoderConfig.registerEncoder(CacheStrategy.Companion.class, zzdv.zza);
        encoderConfig.registerEncoder(Dimension.class, zzdw.zza);
        encoderConfig.registerEncoder(ImageSource$Metadata.class, zzdu.zza);
        encoderConfig.registerEncoder(Bitmaps.class, zzdx.zza);
        encoderConfig.registerEncoder(HwidLimitDialogKt.class, zzeu.zza);
        encoderConfig.registerEncoder(FilesScreenKt.class, zzet.zza);
        encoderConfig.registerEncoder(FocusStrategy.class, zzbt.zza);
        encoderConfig.registerEncoder(StringMerger.class, zzgx.zza);
        encoderConfig.registerEncoder(zaa.class, zzgz.zza);
        encoderConfig.registerEncoder(zzle.class, zzgy.zza);
        encoderConfig.registerEncoder(DBUtil.class, zzcx.zza);
        encoderConfig.registerEncoder(WorkSpecKt.class, zzdn.zza);
        encoderConfig.registerEncoder(WorkerUpdater.class, zzdm.zza);
        encoderConfig.registerEncoder(WorkDatabasePathHelper.class, zzdl.zza);
        encoderConfig.registerEncoder(PropertiesScreenKt.class, zzfa.zza);
        encoderConfig.registerEncoder(UpdateDialogKt.class, zzfc.zza);
        encoderConfig.registerEncoder(ProvidersScreenKt.class, zzfb.zza);
        encoderConfig.registerEncoder(ExifInterfaceUtils.class, zzca.zza);
        encoderConfig.registerEncoder(zzaw.class, zzcb.zza);
        encoderConfig.registerEncoder(ProfileCardKt.class, zzff.zza);
        encoderConfig.registerEncoder(zzjq.class, zzfi.zza);
        encoderConfig.registerEncoder(zzjo.class, zzfg.zza);
        encoderConfig.registerEncoder(ProxyScreenKt.class, zzfh.zza);
        encoderConfig.registerEncoder(ViewModelKt.class, zzce.zza);
        encoderConfig.registerEncoder(LifecycleEffectKt.class, zzcf.zza);
        encoderConfig.registerEncoder(QrCodeGeneratorKt.class, zzgt.zza);
        encoderConfig.registerEncoder(LocalNetworkKt.class, zzgs.zza);
        encoderConfig.registerEncoder(RemoteKt.class, zzgv.zza);
        encoderConfig.registerEncoder(SuspendTransactionKt.class, zzgw.zza);
        encoderConfig.registerEncoder(TvGlassTabRowKt.class, zzfq.zza);
        encoderConfig.registerEncoder(zzkb.class, zzft.zza);
        encoderConfig.registerEncoder(com.github.kr328.clash.core.util.NetKt.class, zzfr.zza);
        encoderConfig.registerEncoder(TrafficKt.class, zzfs.zza);
        encoderConfig.registerEncoder(NavOptionsBuilderKt.class, zzck.zza);
        encoderConfig.registerEncoder(NavGraph.Companion.class, zzcl.zza);
        encoderConfig.registerEncoder(ApkDownloader.class, zzeg.zza);
        encoderConfig.registerEncoder(SvgUtils.class, zzed.zza);
        encoderConfig.registerEncoder(TvQrCodeSheetKt.class, zzfj.zza);
        encoderConfig.registerEncoder(zzjt.class, zzfl.zza);
        encoderConfig.registerEncoder(zzjs.class, zzfk.zza);
        encoderConfig.registerEncoder(NavArgumentKt.class, zzcg.zza);
        encoderConfig.registerEncoder(zzbc.class, zzch.zza);
    }
}
